---
# Ubuntu related OS tasks

- name: Update apt cache
  apt:
    update_cache: yes

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

# - name: install additional packages
#   apt:
#     name: [nginx-extras,openssl]
#     autoremove: true
#     state: latest

# - name: install needed packages
#   apt:
#     name:
#       - python-pip
#       - python-netaddr
#     state: latest
