---
# tasks file for nfs

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Configure autofs map for NFS share
  ansible.builtin.template:
    src: autofs_nfs_map.j2
    dest: /etc/auto.nfs

- name: Configure autofs master map
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    line: "/var/www/nextcloud/data /etc/auto.nfs"