---
# tasks file for nfs

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Configure autofs map for NFS share
  ansible.builtin.template:
    src: autofs_nfs_map.j2
    dest: /etc/auto.nfs

- name: Configure autofs master map
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    line: "/mnt/nextcloud /etc/auto.nfs --timeout=6000 --ghost"

- name: Restart autofs service
  ansible.builtin.service:
    name: autofs
    state: restarted

- name: Create symlink from /mnt/nextcloud/data to /var/www/nextcloud
  ansible.builtin.file:
    src: /mnt/nextcloud/data
    dest: /var/www/nextcloud
    state: link
    force: yes